INSERT INTO dewey (id, label)
VALUES
  (000, "Généralités"),
  (010, "Bibliographies"),
  (020, "Bibliothéconomie et sciences de l'information"),
  (030, "Encyclopédies générales"),
  (050, "Publications en série d'ordre général"),
  (060, "Organisations générales et muséologie"),
  (070, "Journalisme, édition. Journaux"),
  (080, "Recueils généraux"),
  (090, "Manuscrits et livres rares"),
  (100, "Philosophie et disciplines connexes"),
  (110, "Métaphysique"),
  (120, "Epistémologie, causalité, genre humain"),
  (130, "Phénomènes paranormaux. Pseudo-sciences"),
  (140, "Les divers systèmes philosophiques"),
  (150, "Psychologie"),
  (160, "Logique"),
  (170, "Ethique"),
  (180, "Philosophie antique, médiévale, orientale"),
  (181, "Philosophies de l'Orient"),
  (189, "Philosophie médiévale occidentale"),
  (190, "Philosophie occidentale moderne"),
  (200, "Religion"),
  (210, "Religion naturelle"),
  (220, "Bible"),
  (230, "Théologie doctrinale chrétienne"),
  (240, "Théologie morale et spirituelle"),
  (250, "Eglise locale et ordres religieux"),
  (260, "Théologie et société"),
  (270, "Histoire et géographie de l'Eglise"),
  (280, "Confessions et sectes chrétiennes"),
  (290, "Religion comparée. Autres religions"),
  (300, "Sciences sociales"),
  (301, "Anthropologie et sociologie"),
  (306, "Culture, institutions sociales"),
  (310, "Statistiques"),
  (320, "Science politique"),
  (330, "Economie"),
  (340, "Droit"),
  (350, "Administration publique"),
  (360, "Problèmes et services sociaux. Associations"),
  (370, "Education"),
  (380, "Commerce, communications, transports"),
  (390, "Coutumes, savoir-vivre, folklore"),
  (400, "Langues"),
  (403, "Concordances, dictionnaires, encyclopédies"),
  (410, "Linguistique"),
  (420, "Langue anglaise. Anglo-saxon"),
  (430, "Langues germaniques. Allemand"),
  (440, "Langues romanes. Français"),
  (443, "Dictionnaires du français standard"),
  (450, "Italien, roumain, rhéto-romain"),
  (460, "Langues espagnole et portugaise"),
  (470, "Langues italiques. Latin"),
  (480, "Langues helléniques. Grec"),
  (490, "Autres langues"),
  (500, "Sciences de la nature et mathématiques"),
  (510, "Mathématiques"),
  (520, "Astronomie et sciences connexes"),
  (530, "Physique"),
  (540, "Chimie et sciences connexes"),
  (550, "Sciences de la Terre et des autres mondes"),
  (560, "Paléontologie. Paléozoologie"),
  (570, "Sciences de la vie"),
  (580, "Botanique"),
  (590, "Zoologie"),
  (600, "Technique (Sciences appliquées)"),
  (610, "Sciences médicales. Médecine"),
  (620, "Art de l'ingénieur et activités connexes"),
  (630, "Agriculture et techniques connexes"),
  (640, "Economie domestique. Vie à la maison"),
  (650, "Gestion et services connexes"),
  (660, "Techniques chimiques et techniques connexes"),
  (670, "Fabrication industrielle"),
  (680, "Fabrications pour utilisations spécifiques"),
  (690, "Bâtiment"),
  (700, "Les arts"),
  (710, "Urbanisme. Art du paysage"),
  (720, "Architecture"),
  (730, "Arts plastiques. Sculpture"),
  (740, "Dessin, arts décoratifs et mineurs"),
  (750, "La peinture et les peintures"),
  (760, "Arts graphiques. Gravures"),
  (770, "Photographie et photographies"),
  (780, "Musique"),
  (790, "Loisirs et arts du spectacle"),
  (800, "Littérature (Belles-lettres)"),
  (810, "Littérature américaine en anglais"),
  (820, "Littératures anglaise et anglo-saxonne"),
  (821, "Poésie de langue anglaise"),
  (822, "Littérature dramatique anglaise"),
  (823, "Fiction anglaise"),
  (830, "Littératures des langues germaniques"),
  (840, "Littératures des langues romanes. Littérature française"),
  (850, "Littératures italienne, roumaine, rhéto-romane"),
  (860, "Littératures espagnole et portugaise"),
  (870, "Littératures des langues italiques. Littérature latine"),
  (880, "Littératures helléniques. Littérature grecque"),
  (890, "Littératures des autres langues"),
  (900, "Géographie, histoire, sciences auxiliaires de l'histoire"),
  (910, "Géographie générale. Voyages"),
  (920, "Biographie générale et généalogie"),
  (930, "Histoire générale du monde ancien"),
  (940, "Histoire générale de l'Europe"),
  (944, "Histoire de la France (depuis 486)"),
  (950, "Histoire générale de l'Asie"),
  (960, "Histoire générale de l'Afrique"),
  (970, "Histoire générale rie l'Amérique du Nord"),
  (980, "Histoire générale de l'Amérique du Sud"),
  (990, "Histoire générale des autres pays")
;
